-- Grant remaining roles access to API programs

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R000'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI LIKE '/api/v1%'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R000'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R002'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI LIKE '/api/v1%'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R002'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R003'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI LIKE '/api/v1%'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R003'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R004'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI LIKE '/api/v1%'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R004'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R005'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI LIKE '/api/v1%'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R005'
  );
