-- Seed API program mappings for access control
-- Safe to re-run; each insert checks for existing URI

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Root', '/api', '0', '1', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api');

UPDATE TB_PROGRM
SET UPPER_PROGRM_SN = (SELECT PROGRM_SN FROM TB_PROGRM WHERE PROGRM_URI = '/api' LIMIT 1)
WHERE PROGRM_URI LIKE '/api/v1%'
  AND (UPPER_PROGRM_SN = '0' OR UPPER_PROGRM_SN IS NULL);

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Assets', '/api/v1/assets', '0', '10', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/assets');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Attachments', '/api/v1/attachments', '0', '20', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/attachments');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Business Info', '/api/v1/bsns-info', '0', '30', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/bsns-info');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Code Types', '/api/v1/code-types', '0', '40', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/code-types');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Users', '/api/v1/users', '0', '50', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/users');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Auth', '/api/v1/auth', '0', '60', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/auth');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Program Access', '/api/v1/program-access', '0', '70', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/program-access');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Programs', '/api/v1/programs', '0', '80', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/programs');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Service Response', '/api/v1/sr', '0', '90', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/sr');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Infra Operations', '/api/v1/infra-operations', '0', '100', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/infra-operations');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Functional Improvements', '/api/v1/func-improvements', '0', '110', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/func-improvements');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API WDTB', '/api/v1/wdtb', '0', '120', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/wdtb');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Report Attendance', '/api/v1/report-attendance', '0', '130', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/report-attendance');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Reports', '/api/v1/reports', '0', '140', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/reports');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Report Details', '/api/v1/report-details', '0', '150', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/report-details');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Report Detail V2', '/api/v1/report-details/v2', '0', '160', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/report-details/v2');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Report Chargers', '/api/v1/report-chargers', '0', '170', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/report-chargers');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API Sys Chargers', '/api/v1/sys-chargers', '0', '180', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/sys-chargers');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API SMS', '/api/v1/sms', '0', '190', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/sms');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API History Login', '/api/v1/hist/login', '0', '200', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/hist/login');

INSERT INTO TB_PROGRM(PROGRM_NM, PROGRM_URI, UPPER_PROGRM_SN, SORT_NO, MENU_INDICT_YN, CREAT_DT, CREAT_ID, UPDT_DT, UPDT_ID, DELETE_YN)
SELECT 'API History Use', '/api/v1/hist/use', '0', '210', 'N', NOW(), 'system', NOW(), 'system', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_PROGRM WHERE PROGRM_URI = '/api/v1/hist/use');

-- Grant admin (R001) access to all API programs
-- Adjust roles later via program-access API or direct SQL

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/assets'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/attachments'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/bsns-info'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/code-types'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/users'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/auth'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/program-access'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/programs'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/sr'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/infra-operations'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/func-improvements'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/wdtb'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/report-attendance'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/reports'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/report-details'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/report-details/v2'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/report-chargers'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/sys-chargers'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/sms'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/hist/login'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );

INSERT INTO TB_PROGRM_ACCES_AUTHOR(PROGRM_SN, PROGRM_ACCES_AUTHOR_CODE)
SELECT PG.PROGRM_SN, 'R001'
FROM TB_PROGRM PG
WHERE PG.PROGRM_URI = '/api/v1/hist/use'
  AND NOT EXISTS (
      SELECT 1 FROM TB_PROGRM_ACCES_AUTHOR AA
      WHERE AA.PROGRM_SN = PG.PROGRM_SN
        AND AA.PROGRM_ACCES_AUTHOR_CODE = 'R001'
  );
